In [1]:
# 环境与路径配置
from pathlib import Path
import tarfile
import json
from typing import List, Tuple

import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 200)

PROJECT_ROOT = Path(r"/root/autodl-tmp/Sharebottom_PEPNet")
RAW_DIR = PROJECT_ROOT / "Ali-CCP"
WORK_DIR = PROJECT_ROOT / "datapreprocess" / "workspace"
EXTRACT_DIR = WORK_DIR / "raw_extracted"
OUT_DIR = WORK_DIR / "processed"
REPORT_DIR = WORK_DIR / "reports"

for d in [WORK_DIR, EXTRACT_DIR, OUT_DIR, REPORT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("RAW_DIR:", RAW_DIR)
print("WORK_DIR:", WORK_DIR)

PROJECT_ROOT: /root/autodl-tmp/Sharebottom_PEPNet
RAW_DIR: /root/autodl-tmp/Sharebottom_PEPNet/Ali-CCP
WORK_DIR: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace

In [ ]:
# # 解压 tar.gz 文件
# archives = sorted(RAW_DIR.glob("*.tar.gz"))
# print("Found archives:")
# for a in archives:
#     print(" -", a.name)

# for arc in archives:
#     target = EXTRACT_DIR / arc.stem.replace('.tar', '')
#     target.mkdir(parents=True, exist_ok=True)
#     with tarfile.open(arc, "r:gz") as tf:
#         tf.extractall(target)
#     print(f"Extracted: {arc.name} -> {target}")

# print("\nExtract done.")

In [2]:
# 扫描解压目录并推断文件角色（skeleton/common）
all_files = [p for p in EXTRACT_DIR.rglob('*') if p.is_file()]
print(f"Total extracted files: {len(all_files)}")
for p in all_files[:30]:
    print(" -", p)

def guess_role(path: Path) -> str:
    name = path.name.lower()
    if ('skeleton' in name) or (('sample' in name) and ('common' not in name)):
        return 'skeleton'
    if 'common' in name:
        return 'common'
    return 'unknown'

role_map = [(p, guess_role(p)) for p in all_files]
role_df = pd.DataFrame([(str(p), r) for p, r in role_map], columns=['path', 'role'])

display(role_df.groupby('role').size().rename('count').reset_index())
display(role_df.head(50))

Total extracted files: 4
 - /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_test/common_features_test.csv
 - /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_test/sample_skeleton_test.csv
 - /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_train/common_features_train.csv
 - /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_train/sample_skeleton_train.csv

       role  count
0    common      2
1  skeleton      2

                                                path      role
0  /root/autodl-tmp/Sharebottom_PEPNet/dataprepro...    common
1  /root/autodl-tmp/Sharebottom_PEPNet/dataprepro...  skeleton
2  /root/autodl-tmp/Sharebottom_PEPNet/dataprepro...    common
3  /root/autodl-tmp/Sharebottom_PEPNet/dataprepro...  skeleton

In [3]:
# 手工指定 train/test 的 skeleton/common 文件路径（明确指定解压后的4个CSV文件）
TRAIN_SKELETON = EXTRACT_DIR / "sample_train" / "sample_skeleton_train.csv"
TRAIN_COMMON = EXTRACT_DIR / "sample_train" / "common_features_train.csv"
TEST_SKELETON = EXTRACT_DIR / "sample_test" / "sample_skeleton_test.csv"
TEST_COMMON = EXTRACT_DIR / "sample_test" / "common_features_test.csv"

# 此处打印检查，避免错误
print("TRAIN_SKELETON:", TRAIN_SKELETON, "Exists:", TRAIN_SKELETON.exists())
print("TRAIN_COMMON:", TRAIN_COMMON, "Exists:", TRAIN_COMMON.exists())
print("TEST_SKELETON:", TEST_SKELETON, "Exists:", TEST_SKELETON.exists())
print("TEST_COMMON:", TEST_COMMON, "Exists:", TEST_COMMON.exists())

assert TRAIN_SKELETON.exists(), "找不到 TRAIN_SKELETON"
assert TRAIN_COMMON.exists(), "找不到 TRAIN_COMMON"
assert TEST_SKELETON.exists(), "找不到 TEST_SKELETON"
assert TEST_COMMON.exists(), "找不到 TEST_COMMON"

TRAIN_SKELETON: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_train/sample_skeleton_train.csv Exists: True
TRAIN_COMMON: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_train/common_features_train.csv Exists: True
TEST_SKELETON: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_test/sample_skeleton_test.csv Exists: True
TEST_COMMON: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/raw_extracted/sample_test/common_features_test.csv Exists: True

### 模型输入处理 (对齐 Sharebottom + PEPNet 架构)

接下来的处理紧扣您的架构设计：
1. **统一解析并构建全局词表 (Vocab Generator)**：过滤低频词，统一将 `(field_id, feature_id)` 映射为从 2 开始的稠密整数索引，0给 Padding，1给 OOV (Out of Vocabulary)。
2. **特征分流映射 (Feature Routing)**：在单条样本遍历合并 `skeleton` 与 `common` 时，依据定义的四个大类分组，把特征提取并分块写入最终格式里，使得 `DataLoader` 只需原样吐出张量：
    - `'epnet_scene'` $\rightarrow$ **EPNet 场景特异性底座**
    - `'user_profile'` / `'user_behavior'` $\rightarrow$ **Gate NN 个性化滤镜 & PPNet 参数微调**
    - `'item_and_cross'` $\rightarrow$ **大哥塔 (Click Tower) 底层共享底座**
3. **清洗与导出**：过滤掉所有 `y=0, z=1` 的非法标签，并且额外生成 `sample_weight_conv` 对抗严重的不平衡问题，最后将每个样本导成 Parquet。

In [ ]:
import gc
import pickle
import json
from collections import defaultdict
import pyarrow as pa
import pyarrow.parquet as pq
import sqlite3

# ========================================
# 1. 核心解析逻辑与架构强相关的特征划分
# ========================================
SEP_LIST = '\x01' # 快递列表分隔符
SEP_FID = '\x02'  # 区分“这是什么类型的包裹(Field)”和“里面装了什么(ID)”的分隔符
SEP_IDV = '\x03'  # 区分“具体是什么ID”和“它的重要程度是多少(Value)”的分隔符

#将特定 field 强制定向到 4 个网络组件路径
FIELD_GROUP = {
    'epnet_scene': ['301'], # 走下路进入 EPNet 做全局缩放
    'user_profile': ['101', '121', '122', '124', '125', '126', '127', '128', '129'], # 走上路提供给 Gate NN 与 PPNet
    'user_behavior': ['109_14', '110_14', '127_14', '150_14'],                       # 同上，走上路的个性化门控
    'item_and_cross': ['205', '206', '207', '210', '216', '508', '509', '702', '853']  # 走底座并被 "click 塔" 吸收
}

def parse_features_line(feat_str: str):
    """把极其松散的 feature_list 解析为 {field_id: [(feature_id, feature_value)...]} 字典"""
    res = defaultdict(list)
    if pd.isna(feat_str) or not feat_str: return res
    for item in str(feat_str).split(SEP_LIST):
        if not item or SEP_FID not in item: continue
        try:
            fid, rest = item.split(SEP_FID, 1)
            if SEP_IDV in rest:
                feat_id, feat_val = rest.split(SEP_IDV, 1)
            else:
                feat_id, feat_val = rest, '1.0'
            res[fid.strip()].append((feat_id.strip(), float(feat_val)))
        except: pass
    return res

# parse_features_line 函数在干什么？ 假如输入（它收到的原始字符串）是："301\x02456\x031.0\x01101\x02abc\x031.0"
#     split(SEP_LIST) 会把它劈成两个小块："301\x02456\x031.0" 和 "101\x02abc\x031.0"
#     split(SEP_FID) 劈开第一个小块，得到领域 fid = "301", 和内容 "456\x031.0"
#     split(SEP_IDV) 劈开内容，得到特征 feat_id = "456", 值 feat_val = 1.0 得到什么：最终将那堆乱码变成一个规整的字典：{"301": [("456", 1.0)], "101": [("abc", 1.0)]}。

In [ ]:
# ========================================
# 2. 从头扫描一次，构建全局共享词表 (仅依赖 Train 避免泄露)
# ========================================
MIN_FREQ = 5 # 极低频特征直接丢去 OOV (idx=1)
field_vocab_counter = defaultdict(lambda: defaultdict(int))

def count_vocab(filepath, has_labels=True, chunksize=300_000):
    # Skeleton 与 Common 格式有略微不同
    target_col_idx = 5 if has_labels else 2
    for chunk in pd.read_csv(filepath, header=None, chunksize=chunksize, usecols=[target_col_idx], names=['feature_list'], dtype=str):
        for f_str in chunk['feature_list']:
            parsed = parse_features_line(f_str)
            for fid, fvals in parsed.items():
                for f_id, _ in fvals:
                    field_vocab_counter[fid][f_id] += 1

In [ ]:

print("\n== 1. 开始构建全局词表 (Vocab Generator) ==")
print("-> Scanning TRAIN_COMMON...")
count_vocab(TRAIN_COMMON, has_labels=False)
print("-> Scanning TRAIN_SKELETON...")
count_vocab(TRAIN_SKELETON, has_labels=True)


global_vocab = {}
vocab_sizes = {}
for fid, counter in field_vocab_counter.items():
    # 截断低频，并生成密集 Index (0为 padding留用，1为 OOV留用)
    valid_feats = [feat for feat, count in counter.items() if count >= MIN_FREQ]
    feat_to_idx = {feat: idx + 2 for idx, feat in enumerate(valid_feats)}  #enumerate 为它们打上 0, 1, 2... 的标号，然后 +2。意味着最开始的有效ID是 2。
    global_vocab[fid] = feat_to_idx # 保存对照表
    vocab_sizes[fid] = len(feat_to_idx) + 2 
#得到了什么： 得到了字典 global_vocab { "301": { "456": 2, "789": 3 ...}, ... }。 保存了 vocab_sizes.json (记录了每个领域有多少张身份证)。在你未来用 Pytorch 写模型时，你直接读取这个 json，把它传给 nn.Embedding(vocab_size, embedding_dim)，不浪费一丝显存。

with open(OUT_DIR / 'global_vocab.pkl', 'wb') as f:
    pickle.dump(global_vocab, f)
with open(OUT_DIR / 'vocab_sizes.json', 'w') as f:
    json.dump(vocab_sizes, f, indent=2)

print(f"✅ 全局词表构建完成! 共有 {len(global_vocab)} 个维度(Field).")
for f in ['301', '101', '205']:
    if f in vocab_sizes:
        print(f"   - [Field {f}] 词表大小: {vocab_sizes[f]}")

== 1. 开始构建全局词表 (Vocab Generator) ==
-> Scanning TRAIN_COMMON...
-> Scanning TRAIN_SKELETON...
-> Scanning TRAIN_SKELETON...
✅ 全局词表构建完成! 共有 23 个维度(Field).
   - [Field 301] 词表大小: 5
   - [Field 101] 词表大小: 2
   - [Field 205] 词表大小: 912397
✅ 全局词表构建完成! 共有 23 个维度(Field).
   - [Field 301] 词表大小: 5
   - [Field 101] 词表大小: 2
   - [Field 205] 词表大小: 912397

In [5]:
# 如果你是重新打开 notebook，需要确保先加载之前处理好的 global_vocab
if 'global_vocab' not in globals():
    print("⏳ 正在从本地读取 global_vocab.pkl ...")
    with open(OUT_DIR / 'global_vocab.pkl', 'rb') as f:
        global_vocab = pickle.load(f)
    print(f"✅ global_vocab 恢复成功! 共有 {len(global_vocab)} 个维度(Field).")

⏳ 正在从本地读取 global_vocab.pkl ...
✅ global_vocab 恢复成功! 共有 23 个维度(Field).
✅ global_vocab 恢复成功! 共有 23 个维度(Field).

In [6]:
# ========================================
# 3.1 构建 Common SQLite DB
# ========================================
def build_common_sqlite_db(com_path):
    com_db_path = OUT_DIR / f"{com_path.stem}.db"
    if com_db_path.exists():
        print(f"-> 发现已存在的 Common DB: {com_db_path}，跳过构建。")
        return com_db_path

    print(f"-> 正在构建 Common SQLite DB: {com_db_path} (一次性扫描文件，但内存占用低) ...")
    conn = sqlite3.connect(str(com_db_path))
    cur = conn.cursor()
    cur.execute('CREATE TABLE IF NOT EXISTS common (common_idx TEXT PRIMARY KEY, feature_list TEXT)')
    conn.commit()
    # 使用事务批量写入以加速
    insert_sql = 'INSERT OR REPLACE INTO common(common_idx, feature_list) VALUES (?, ?)' 
    batch = []
    batch_size = 20000
    for i, row in enumerate(pd.read_csv(com_path, header=None, usecols=[0, 2], names=['common_idx', 'feature_list'], dtype=str, chunksize=100000)):
        for _, r in row.iterrows():
            batch.append((r['common_idx'], r['feature_list']))
            if len(batch) >= batch_size:
                cur.executemany(insert_sql, batch)
                conn.commit()
                batch = []
        # 小的进度打印
        print(f"    - 已扫描 { (i+1) * 100000 } 行 common 文件...", end='\r')
    if batch:
        cur.executemany(insert_sql, batch)
        conn.commit()
    cur.execute('CREATE INDEX IF NOT EXISTS idx_common_idx ON common(common_idx)')
    conn.commit()
    cur.close()
    conn.close()
    print(f"\n-> Common SQLite DB 构建完成: {com_db_path}")
    return com_db_path

In [7]:
# ========================================
# 3.2 数据集 Join 与 模型级 Tensor 数据装配
# ========================================
def process_dataset_to_model_ready_parquet(skel_path, com_path, out_file, vocab, is_train=True, chunksize=150_000):
    print(f"\n== 处理 {'Train' if is_train else 'Test'} 面向模型的输入集 ==")
    
    com_db_path = OUT_DIR / f"{com_path.stem}.db"
    if not com_db_path.exists():
        raise FileNotFoundError(f"找不到 Common DB: {com_db_path}，请先执行构建。")

    # 打开 DB 连接（读模式）
    conn = sqlite3.connect(str(com_db_path))
    cur = conn.cursor()

    print(f"-> 流式转换 Skeleton 并 Join ({skel_path.name})...")
    
    parquet_writer = None
    total_rows = 0
    chunk_count = 0

    for chunk in pd.read_csv(skel_path, header=None, chunksize=chunksize, 
                             usecols=[0, 1, 2, 3, 5], 
                             names=['sample_id', 'click', 'conversion', 'common_idx', 'feature_list'], 
                             dtype={'click': float, 'conversion': float, 'common_idx': str, 'feature_list': str}):
        # 处理标签，并清洗掉（点击=0，转化=1）这种非法漏斗数据
        chunk['click'] = chunk['click'].fillna(0).astype(int)
        chunk['conversion'] = chunk['conversion'].fillna(0).astype(int)
        if is_train:
            chunk = chunk[~((chunk['click'] == 0) & (chunk['conversion'] == 1))]

        # 提取本 chunk 需要的 common_idx 列表，去重以减少 DB 查询开销
        needed_common = chunk['common_idx'].dropna().unique().tolist()

        com_dict = {}
        if needed_common:
            # 分批查询，避免生成过长的 IN 子句
            batch_size = 1000
            for i in range(0, len(needed_common), batch_size):
                sub = needed_common[i:i+batch_size]
                placeholders = ','.join(['?'] * len(sub))
                sql = f"SELECT common_idx, feature_list FROM common WHERE common_idx IN ({placeholders})"
                cur.execute(sql, sub)
                for k, v in cur.fetchall():
                    com_dict[k] = parse_features_line(v)

        records = []
        for _, row in chunk.iterrows():
            feats_skel = parse_features_line(row['feature_list'])
            feats_com = com_dict.get(row['common_idx'], {})

            # 合并当前 Sample 的两个特征集
            all_feats = defaultdict(list)
            for f_dict in [feats_skel, feats_com]:
                for fid, fvals in f_dict.items():
                    all_feats[fid].extend(fvals)

            record = {
                'sample_id': row['sample_id'],
                'click': row['click'],
                'conversion': row['conversion'],
                'sample_weight_conv': 5.0 if row['conversion'] == 1 else 1.0 
            }

            for group_name, fids in FIELD_GROUP.items():
                group_indices = []
                group_values = []
                for fid in fids:
                    for feat_id, feat_val in all_feats.get(fid, []):
                        idx = vocab.get(fid, {}).get(feat_id, 1) # OOV(1)
                        group_indices.append(idx)
                        group_values.append(feat_val)
                record[f'{group_name}_idx'] = group_indices
                record[f'{group_name}_val'] = group_values

            records.append(record)

        if not records:
            continue

        chunk_df = pd.DataFrame(records)
        table = pa.Table.from_pandas(chunk_df)

        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(out_file, table.schema)

        parquet_writer.write_table(table)

        total_rows += len(chunk_df)
        chunk_count += 1
        print(f"     已落盘 Chunk {chunk_count} ({total_rows} 行)...")

        del chunk_df
        del table
        del records
        gc.collect()

        if chunk_count >= 10:
            print(f"     [!] 达到抽样阈值 (10 Chunks)，提前结束该数据集处理。")
            break

    if parquet_writer is not None:
        parquet_writer.close()

    cur.close()
    conn.close()

    print(f"✅ Saved: {out_file.name}, 有效样本数: {total_rows}")

In [ ]:
# ========================================
# 3.3 执行 - 构建 SQLite DB
# ========================================
print("正在检查并构建 Common SQLite DB...")
#build_common_sqlite_db(TRAIN_COMMON)
build_common_sqlite_db(TEST_COMMON)
print("DB 检查/构建完成！")

正在检查并构建 Common SQLite DB...
-> 正在构建 Common SQLite DB: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/processed/common_features_train.db (一次性扫描文件，但内存占用低) ...
    - 已扫描 800000 行 common 文件...
-> Common SQLite DB 构建完成: /root/autodl-tmp/Sharebottom_PEPNet/datapreprocess/workspace/processed/common_features_train.db
DB 检查/构建完成！

In [9]:
# ========================================
# 3.4 执行 - 处理数据并落盘
# ========================================
#process_dataset_to_model_ready_parquet(TRAIN_SKELETON, TRAIN_COMMON, OUT_DIR / 'train_model_input.parquet', global_vocab, is_train=True)
process_dataset_to_model_ready_parquet(TEST_SKELETON, TEST_COMMON, OUT_DIR / 'test_model_input.parquet', global_vocab, is_train=False)

print("\n🎉 数据预处理与张量映射全部完成！")

== 处理 Test 面向模型的输入集 ==
-> 流式转换 Skeleton 并 Join (sample_skeleton_test.csv)...
     已落盘 Chunk 1 (150000 行)...
     已落盘 Chunk 1 (150000 行)...
     已落盘 Chunk 2 (300000 行)...
     已落盘 Chunk 2 (300000 行)...
     已落盘 Chunk 3 (450000 行)...
     已落盘 Chunk 3 (450000 行)...
     已落盘 Chunk 4 (600000 行)...
     已落盘 Chunk 4 (600000 行)...
     已落盘 Chunk 5 (750000 行)...
     已落盘 Chunk 5 (750000 行)...
     已落盘 Chunk 6 (900000 行)...
     已落盘 Chunk 6 (900000 行)...
     已落盘 Chunk 7 (1050000 行)...
     已落盘 Chunk 7 (1050000 行)...
     已落盘 Chunk 8 (1200000 行)...
     已落盘 Chunk 8 (1200000 行)...
     已落盘 Chunk 9 (1350000 行)...
     已落盘 Chunk 9 (1350000 行)...
     已落盘 Chunk 10 (1500000 行)...
     [!] 达到抽样阈值 (10 Chunks)，提前结束该数据集处理。
✅ Saved: test_model_input.parquet, 有效样本数: 1500000

🎉 数据预处理与张量映射全部完成！
     已落盘 Chunk 10 (1500000 行)...
     [!] 达到抽样阈值 (10 Chunks)，提前结束该数据集处理。
✅ Saved: test_model_input.parquet, 有效样本数: 1500000

🎉 数据预处理与张量映射全部完成！

In [10]:
# ========================================
# 4. 数据质量检视 (测试直接喂给 DataLoader 的长相)
# ========================================
print("== 加载组装好的 Train Parquet 预览 ==")
final_train_df = pd.read_parquet(OUT_DIR / 'train_model_input.parquet')
display(final_train_df.head())

print("\n[Click/CTR 均值]:", final_train_df['click'].mean())
print("[Conversion/CVR 均值]:", final_train_df['conversion'].mean())

print("\nEPNet 输入特征数组示例 (第一条数据):")
print("EPNet index:", final_train_df.iloc[0]['epnet_scene_idx'])

print("\nGate NN 用户侧特征数组示例 (第一条数据):")
print("Profile index:", final_train_df.iloc[0]['user_profile_idx'])
print("Behavior index:", final_train_df.iloc[0]['user_behavior_idx'])

== 加载组装好的 Train Parquet 预览 ==

,sample_id,click,conversion,sample_weight_conv,epnet_scene_idx,epnet_scene_val,user_profile_idx,user_profile_val,user_behavior_idx,user_behavior_val,item_and_cross_idx,item_and_cross_val
0,1,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[117, 1290, 116, 10, 11, 244, 877, 124, 3193, ...","[0.69315, 1.79176, 4.40672, 3.29584, 5.14166, ...","[2, 2, 2, 2, 3, 4, 2, 2]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.69315]"
1,2,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[117, 1290, 116, 10, 11, 244, 877, 124, 3193, ...","[0.69315, 1.79176, 4.40672, 3.29584, 5.14166, ...","[3, 3, 3, 5, 6, 7, 8, 9, 3]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
2,3,1,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[117, 1290, 116, 10, 11, 244, 877, 124, 3193, ...","[0.69315, 1.79176, 4.40672, 3.29584, 5.14166, ...","[4, 4, 4, 10, 11, 12, 13, 14, 15, 16, 17, 18, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
3,4,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[117, 1290, 116, 10, 11, 244, 877, 124, 3193, ...","[0.69315, 1.79176, 4.40672, 3.29584, 5.14166, ...","[5, 5, 5, 21, 22, 23, 24, 5, 4, 3, 4, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.397..."
4,5,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[117, 1290, 116, 10, 11, 244, 877, 124, 3193, ...","[0.69315, 1.79176, 4.40672, 3.29584, 5.14166, ...","[1, 6, 6, 25, 26, 27, 6, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.29584]"

[Click/CTR 均值]: 0.046610435030726954
[Conversion/CVR 均值]: 0.00028600266935824737

EPNet 输入特征数组示例 (第一条数据):
EPNet index: [2]

Gate NN 用户侧特征数组示例 (第一条数据):
Profile index: [1 4 2 2 2 2 2 5]
Behavior index: [   117   1290    116     10     11    244    877    124   3193    126
    127    422    201    852   2292     33   4284     35   1110   1056
     96    348   2310      7    167     12   4770   2171     90    256
   1388    646    645     24    164   2050   1676   3196    489    644
    643   4498     31     32    282    785   1052     78   1228   2316
    159    488     76    157    860    156   1984    538   1418      2
     71    743     70    188    153      9   1586     14    381     16
     19   1020   4942     23   2126   1374   2943    308    705     25
     64     30    146     62    599     61    754   1132    466     56
    354   1915   1822     52     51      5    136      6    459   2945
    454   2160   1752     47    670     17     20    134     29    956
   1081   2754   2674    280   2339    130    225 125168 329414  12090
  12686  28649  59234  37644 158992 257892 236893 206935  37649 675154
 111426 503197 132593    960 269979  41828 937266 266882 183571  35156
  84968  60395      1 585378   1129 557204 450232 240958    391  18332
  91364  21519 417088  46959 314378 100499 601456  33034 490639 257902
   3193 143116 171353 370951  61204 110161   3187 271885 253191 730898
  28678 287029  72845  10755 937267 292139 100922  72041 169562  50096
  36832 205665  77733  40480 937268  40304  11541 469987 394273 147989
 281045  59087  30540 372374  32391   4455 497747 196078  37690 513502
 377223 120341   4452   5629 596396 218375  46565 621849 149977  60470
 823812   1029   1031 212373 253197 403700   3024   1197 154815 326866
 193994 102084 479141  47359 165697 937269 502973 937270  46580 285634
 189723  11340   4579  30563  77500 100754   9752   1824   7461  33367
  43859  62132  40924   1226  40450 364527  25726 178671  81119   1227
  11592  59187  12760  28818   5701 253209 557224 174913 430605  18735
 135057      1  12010   3237 261835 298748   4184   9132  48954   9135
  35050 937271      1 532168  40836  94552 100086  53343  38273 937272
 213430      1  59174  17409  40419  29485 643339  36227  23147 497777
 122584  23457 676449 937273   9701  66038 148037 191983 164265  40247
 296987 806809 569752 534468 647384 715506  68148  47865   2957 264239
   2060      1 284461  77980  59160  29498   1555 253111 497782 143908
 937274 156731 156457  74799  20377   2415 116638  58366 266948  80962
 143359  20945 221260  77530      1   4142  94432 289932  54933 104242
   3317 351627  35091 131290 288144 121418   4134  28682  36896  65659
  10773 271510  32277 501875 835583 937275 108219  40220   3298 263728
  57836 389136 158962  42901  75188 143882  59148 112467  21959   2918
    785  40891 148887 182422   1017  18531 139656 168315 430654 112516
 241170 192967    540 936182   2117 375203  11124  42212   3706 891740
  27203 544376 202876 108507  11353 101861  75891   1605 239841  89542
   8762 406078   1048  17366 581359   8108 645518  37610  11688    146
 209112 140591 494071  71801 164190 292937 459072   7901 293284 138982
  40184   4076 263903 222766      1 187454  10865 139122 459712 937276
  30304 196779  18732      1  40349 298730 129184  56504  55469   7348
  38720 233681 376216 149172  37624 585799  30293  62755  39963 890615
 314855 937264 311383 196784  33051 937265  56569  88044  72341  12915
   2964  15061  34980    227  27800     10  28304  26682   9666   2423
   3246   9301  82388    209  14748  24219   4988   6191  13101   2541
   1001   1825   1404   1007    190 192170  55821    186     40   5310
   1823  59110   7225    678    560  29887 153703  44391    956   1814
  20174    875    472 126882  16972  52623   1741  83454    464  25084
   1738   1635  72701  54845  19814  61732    707  15090   2017  18988
   6099 126796   6802   1720   2558   4805   5495    617  35000  53701
   1355  14749 224606  81312  12090    434  23659  61163   7453 125236
   2883  17005   2324    840    407  26451  96048  29157   8162    584
  14762  77620    401   1323 106139 113300  40276 130494  43933  59448
      6  12673    234   1685  33678   7676  23322 176754 146825  20935
    219  38419  35272  95134    210   4366  49808  44196   5632  21234
  60426  20093   2287   1091 148715  27605  64553   9128 156411  10577
   7414   6929  93377    366   5067    566   1049  29886 127096   9232
 227481   9771  27558  20072   2827      2  48834 220383   2640  17923
   2247   8628      8   4901   1149  53648  81853      1  20408  35968
  16723    132  12902  28212  12080  23646  12081  20811  90837   9788
  62452  61080    546  20059    728  14273   4804   9401   6737    557
      1   7390  88594  60649   2695  12248  14491  59710  25260   6449
   2454  46966  12193  32511  16779   1743  33578 172399   3770  10352
 243948    317  75997  29166   9669    241  15200   3996   1156    427
   5943    572    573   1721    484   1157   5875  33007   5811    421
   1487   2834  91264  13286   5756    416   1089  14164  19720  14162
    368     11    410   9351   1709   1886   1885   1253  33833   5100
   2683  13171    404  26891   3835   5150  56742    707  31652    200
  13773  29418    198   7978   1263   4758  26623  32882  44961  45507
   1774   5193  10342   5192  18045  91851    393    392  14658  13164
  54674   1274    390  54405   4766    387    385  10856  26604   5142
  14154   1680  53860  11838     46  89884   4773    517  25422   4877
   1109  29441  13156  18403  14151     59   1436  47647  16438  11313
  21664    641    931  31156  12310    370   3224    635    362   2835
  82995   5176  66272   5794  13150    267    480    532  20307  18397
  23010    694    262   1117   1226  14146    536    258  17538  62324
     85    946   6691   4049    468   4389   4784  20038    251   3676
  56911    151    249  20896    709  26611    461   1850  15481  89647
    609  16504   1579   1198  35842   3112    457    143    454    450
  10569    238   9032   3627  30430  80989    807    720    444  14128
   2798    336   3962    724    963    594  18470    438   2191    560
   5451  15862   3730   2836    347   4797  82289   5952   1604    735
  17420    982   9798   3650  74079   2420  14113    357    218]

In [11]:
# ========================================
# 4. 数据质量检视 (测试直接喂给 DataLoader 的长相)
# ========================================
print("== 加载组装好的 Test Parquet 预览 ==")
final_train_df = pd.read_parquet(OUT_DIR / 'test_model_input.parquet')
display(final_train_df.head())

print("\n[Click/CTR 均值]:", final_train_df['click'].mean())
print("[Conversion/CVR 均值]:", final_train_df['conversion'].mean())

print("\nEPNet 输入特征数组示例 (第一条数据):")
print("EPNet index:", final_train_df.iloc[0]['epnet_scene_idx'])

print("\nGate NN 用户侧特征数组示例 (第一条数据):")
print("Profile index:", final_train_df.iloc[0]['user_profile_idx'])
print("Behavior index:", final_train_df.iloc[0]['user_behavior_idx'])

== 加载组装好的 Test Parquet 预览 ==

,sample_id,click,conversion,sample_weight_conv,epnet_scene_idx,epnet_scene_val,user_profile_idx,user_profile_val,user_behavior_idx,user_behavior_val,item_and_cross_idx,item_and_cross_val
0,1,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[1720, 117, 1290, 1746, 116, 10, 11, 731, 244,...","[1.09861, 0.69315, 1.79176, 1.09861, 4.51086, ...","[102, 28, 75, 430, 46622, 429, 426, 424, 427, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
1,2,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[1720, 117, 1290, 1746, 116, 10, 11, 731, 244,...","[1.09861, 0.69315, 1.79176, 1.09861, 4.51086, ...","[43, 25, 53, 200, 228, 199, 2870, 198, 24176, ...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
2,3,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[1720, 117, 1290, 1746, 116, 10, 11, 731, 244,...","[1.09861, 0.69315, 1.79176, 1.09861, 4.51086, ...","[23239, 13, 13289, 10893, 16082, 26891, 403, 1...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."
3,4,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[1720, 117, 1290, 1746, 116, 10, 11, 731, 244,...","[1.09861, 0.69315, 1.79176, 1.09861, 4.51086, ...","[1, 9, 75, 273, 48, 47, 1, 7, 19, 34]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.02535, 2..."
4,5,0,0,1.0,[2],[1.0],"[1, 4, 2, 2, 2, 2, 2, 5]","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[1720, 117, 1290, 1746, 116, 10, 11, 731, 244,...","[1.09861, 0.69315, 1.79176, 1.09861, 4.51086, ...","[70759, 18, 56347, 132, 151, 10048, 133, 15214...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ..."

[Click/CTR 均值]: 0.04698733333333333
[Conversion/CVR 均值]: 0.00034933333333333333

EPNet 输入特征数组示例 (第一条数据):
EPNet index: [2]

Gate NN 用户侧特征数组示例 (第一条数据):
Profile index: [1 4 2 2 2 2 2 5]
Behavior index: [   1720     117    1290    1746     116      10      11     731     244
     877     802     516     182     124    3193     126     127    1435
     422     201     177     202     176    2576    1531     852    2292
      33    4284     624      35      36    1110     118    1056      96
     348     524    2310      93       7     167      12    4770    2171
      90      88     256    1388    1209     565     646     645      24
     164    2050    1676     540    3196     489     644     643    4498
      31      32     555     161     785     282    1052      78    1228
    2316     159     488     487     377      76     157     714     860
     125     156     154    1984     538    1418       2      71     743
      70     188     153     770       9     712      14     381      16
     150      19    6365    1020     148    4942      23    2126    1374
    2943     308     705      25      64    1871      30     146     698
    3889      62      61     599      34     754    1132    2500     466
      56     354    1915    1822      52     850      51       5     136
       6     780     459     455    2945     454    2160    1752      47
     670    2048      17      20     236     134      29     956    2239
    1081    2754    2674     280     556     446     666    1560    2339
     283     130     225   72341  125168  329414   12090   12686   28649
   59234   37644  158992  257892  236893  155165   67017  206935   37649
  675154  111426  503197  132593     960  269979   41828  937266   84619
  266882  183571   35156   84968   60395       1  585378    1129  557204
  450232  240958     391  606224   13224   18332   91364   21519  417088
   46959  314378     385  100499  601456   33034  490639  257902  202525
    3193  143116   68057  171353  370951   61204  110161    3187  271885
  253191  730898   40069   28678  287029   72845   10755  937267  292139
  100922  327243   72041  169562   84877   50096  448985   36832  205665
   77733   40480  937268   40304   11541   23193  469987  394273  147989
  281045   59087   30540  372374   32391    4455  497747  196078   37690
  513502  377223  120341    4452    5629  596396  218375   46565   54156
  621849  149977   35017  255946   22358   60470  823812    1029   14111
    1031  212373  253197  403700    3024    1197  154815  326866  193994
  539347  102084  479141   47359  187566  165697  937269  502973  937270
   46580  285634  189723   11340    4579   30563   77500   24184  100754
    3139    9752    1824    7461   33367   43859   62132   40924    1226
   40450  364527   25726  178671   81119    1227   43857   11592   59187
   12760   28818    5701    8207  253209  557224  174913  430605   18735
  135057       1   12010    3237  261835  298748    4184    9132   48954
    9135  801789   35050  937271       1  532168   40836   94552  100086
   53343   38273  937272  224924  213430       1   59174   17409   40419
   29485  643339   36227    6657   23147  497777    6732  122584   23457
  676449  937273    9701   66038  148037  191983  164265   40247  296987
  806809  569752  534468  647384  715506   68148   47865    2957  264239
    2060       1  284461   77980   59160   29498    1555  253111  342490
  497782 1095639  143908  937274  156731  156457   74799   20377    2415
  116638   58366  266948   80962  143359   20945  221260   77530       1
    4142   94432  289932   54933  104242    3317  351627   35091  131290
  288144  121418    4134   28682   36896   65659   10773  271510   32277
  501875  835583  937275  108219   40220    3298  263728   57836  389136
  158962   42901   75188  143882   59148  112467   21959    2918     785
   40891   82638  148887  182422    1017   18531  139656  168315  156177
  430654  112516  241170  192967   93839     540  936182    2117  375203
   11124   42212    3706  891740   27203  544376  202876  108507   11353
   75891  101861   49078    1605  239841   89542    8762       1  406078
    1048   17366  581359    8108  645518   37610   11688     146  209112
  140591  494071  214084  135698   71801  164190   37766  292937  459072
    7901  293284  138982   40184    4076  263903  222766       1  187454
   10865  139122  459712  937276   30304  196779   18732  259303       1
   40349  298730  129184   56504   55469    7348   55851  177893   38720
  233681  376216  149172   37624  585799   30293   62755   39963  890615
  314855  937264  311383  196784   33051  937265   56569   88044   12915
    2964   18978   15061   82133   34980  171128     227   27800      10
   28304   26682     225    9666    2423   33043    3246    9301   82388
     209   14748   24219   72201    4988    6191   14690   13101    2541
    1001    1825    1404    1007     190  192170   55821     186      40
    5310    1823   59110    7225     678     560   29887  153703   44391
     956    1814   20174     875   87330     472  126882   16972   52623
   92182    1741   83454     464   25084   95765    1738    1635   72701
   54845   19814   61732     148     707   15090   49792    2017   18988
    6099    1726  126796    6802    1720    2558    4805    5495     617
   29746   35000   53701    1355   14749  224606   81312     901   12090
     434   23659   61163    7453   11612  125236    2883   17005    2324
     840   84031     407   26451   96048   29157    8162     584    8328
   14762    3556   77620     401  106139  113300    1737   40276  130494
   43933   59448       6   12673     234    1685   33678    7676   23322
  176754  146825   20935     219   38419   35272   95134     210    4366
     206   49808   44196    5632   21234   20093   60426    2287    1091
    1707  148715   27605   64553    9128  156411   10577    7414    6929
   93377     366    5067     566    1049   29886  127096    9232  227481
     876    9771   27558   20072    2827       2   16177   48834  220383
    2640     928   17923    2247   12579    8628       8     627    4901
    1149   53648   81853      17       1   20408   35968   16723   28212
     132   12902   10602   12080   12081   23646   20811   90837    9788
   62452   61080     546   20059     728    4299   26839   14273    4804
   32001    9401    6737     557       1    7390   26229   88594   75304
   60649    2695   12248   14491   59710   25260    6449    2454   46966
      73   12193   32511   16779    1743   33578  172399    3770   10352
  243948     317   65248   75997   29166    9669     241       1   15200
    3996    1156     427    5943     572    5875    5811   68174    2834
   14165    1500   51050    1709    1253    2683     404   26891    3835
    5150   31652   29418    1263    4758    1774   68929   86906   18045
   91851     393   60202     392     387   21921     385   26604    5142
   14154   11838      46   89884     517   32770   31640   13156   11673
      59    1436     931     362    2835   82995   13150     267   20307
   18397     694      80    1424   14146     258   17538      85    1853
     468   20038    7888     251    3676     249     709   26611     461
    1959    8509    1579    3112     457    4392     454   10569     238
    9032   30430     807    2798     724     963   18470     560   15862
    3730    2836     347   82289    5952    1604   17420     982    3650
    1154     357     573    1721     484    1157   33007     421    1487
   91264   13286    5756     416    1089   14164    9876   14162      11
     410    9351    1886   63081    5100   13171   56742     707     200
   13773     198    7978   26623   32882   44961   45507   10342    5192
   14658   13164   54674    1274     390   54405    4766   10856    7288
    1680   53860    4773   25422    4877    1109   29441   32012    2381
   18403   14151   47647   16438   11313   21664     641   12310     370
    3224     635    5176   66272    5794     532    4002   55216   23010
   30015    1117    1226     536   62324     946    6691    4389    4784
   56496   56911     151    4790   15481     609   16504    1198   35842
     143     450     448    3627     720     444   14128     336    3962
    9037     594    2191    5451    4797     735    9798   74079    2420
   14113]